on: push
name: Continuous integration

jobs:
  lints:
    name: Lints
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Run rustfmt
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo fmt --all -- --check

      - name: Run clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

  tier1:
    name: Tier 1
    needs: lints
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        toolchain:
          - 1.56.0
          - stable
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Check without features
        run: cargo check

      - name: Check with all features enabled
        run: cargo check --all-features

      - name: Run tests
        if: matrix.toolchain == 'stable'
        run: cargo test --all-features

  tier2:
    name: Tier 2
    needs: tier1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # Linux
          - aarch64-unknown-linux-gnu

          # Solaris
          - x86_64-sun-solaris

          # DragonflyBSD
          - x86_64-unknown-dragonfly

          # NetBSD
          - x86_64-unknown-netbsd

          # Android
          - arm-linux-androideabi
          - armv7-linux-androideabi
          - aarch64-linux-android
          - i686-linux-android
    steps:
      - uses: actions/checkout@v1
      - name: Install cross tool
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Run build
        run: |
          cross build --all-features --target=${{ matrix.target }}

  tier2_ios:
    name: Tier 2 (iOS)
    needs: tier1
    runs-on: macOS-latest
    strategy:
      matrix:
        target:
          - armv7-apple-ios
          - armv7s-apple-ios
          - x86_64-apple-ios
          - aarch64-apple-ios
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: Run build
        run: |
          cargo build --all-features --target=${{ matrix.target }}
